const cfg=window.SXPAY_CONFIG||{};const ready=cfg.SUPABASE_URL&&cfg.SUPABASE_URL.startsWith("http")&&cfg.SUPABASE_ANON_KEY&&cfg.SUPABASE_ANON_KEY.length>20;
const sb=ready?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const loginPanel=document.getElementById("loginPanel"),dash=document.getElementById("dashboard"),loginMsg=document.getElementById("loginMsg");
const msg=(el,t,ok=false)=>{el.textContent=t;el.className="msg "+(ok?"ok":"")};
async function start(){if(!sb){msg(loginMsg,"ضع بيانات Supabase في config.js.");return}const {data:{session}}=await sb.auth.getSession();show(session);sb.auth.onAuthStateChange((_e,s)=>show(s));}
function show(s){if(s){loginPanel.hidden=true;dash.hidden=false;document.getElementById("userEmail").textContent=s.user.email;loadPosts()}else{loginPanel.hidden=false;dash.hidden=true}}
document.getElementById("login").onclick=async()=>{const email=document.getElementById("email").value,password=document.getElementById("password").value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)msg(loginMsg,error.message)};
document.getElementById("logout").onclick=()=>sb.auth.signOut();
const fileInput=document.getElementById("image"),preview=document.getElementById("preview");fileInput.onchange=()=>{const f=fileInput.files[0];if(f)preview.innerHTML=`<img class="preview" src="${URL.createObjectURL(f)}">`};
async function upload(file){if(!file)return null;const ext=file.name.split(".").pop().toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from("news-images").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return sb.storage.from("news-images").getPublicUrl(path).data.publicUrl}
document.getElementById("newsForm").onsubmit=async e=>{e.preventDefault();const formMsg=document.getElementById("formMsg");try{msg(formMsg,"جاري الحفظ...");const imageUrl=await upload(fileInput.files[0]);const published=document.getElementById("published").checked;const {error}=await sb.from("posts").insert({title:document.getElementById("title").value.trim(),category:document.getElementById("category").value,excerpt:document.getElementById("excerpt").value.trim(),body:document.getElementById("body").value.trim(),image_url:imageUrl,published,author_id:(await sb.auth.getUser()).data.user.id,published_at:published?new Date().toISOString():null});if(error)throw error;msg(formMsg,"تم نشر الخبر بنجاح.",true);e.target.reset();preview.innerHTML="";loadPosts()}catch(err){msg(formMsg,err.message)}};
async function loadPosts(){const box=document.getElementById("posts");const {data,error}=await sb.from("posts").select("id,title,category,published,created_at").order("created_at",{ascending:false}).limit(30);if(error){box.innerHTML='<p class="muted">تعذر تحميل الأخبار.</p>';return}box.innerHTML=(data||[]).map(n=>`<div class="post-row"><div><b>${esc(n.title)}</b><small>${esc(n.category)} · ${n.published?"منشور":"مسودة"}</small></div><button class="danger" data-id="${n.id}">حذف</button></div>`).join("")||'<p class="muted">لا توجد أخبار.</p>';box.querySelectorAll(".danger").forEach(b=>b.onclick=()=>deletePost(b.dataset.id))}
async function deletePost(id){if(!confirm("حذف الخبر؟"))return;const {error}=await sb.from("posts").delete().eq("id",id);if(error)alert(error.message);else loadPosts()}
function esc(s=""){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
start();